[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# React Router / Vite SPA redirect
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
